# Project information
site_name: 'LenoxBot Documentation'
site_description: 'LenoxBot offers many cool new features to your Discord Server!'
site_author: 'LenoxBot'
site_url: 'https://lenoxbot.com'

# Repository
repo_name: 'LenoxBot/LenoxBot-Docs'
repo_url: 'https://github.com/LenoxBot/LenoxBot-Docs'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 LenoxBot'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/lenoxbot'
    - type: 'github'
      link: 'https://github.com/LenoxBot/LenoxBot-Docs/'

#Pages
pages:
    - 'index.md'
    - Getting started: gettingstarted.md
    - General FAQ:
      - Bot:
        - 'Test': 'General FAQ/Bot/test1.md'
      - Help:
        - 'Test': 'General FAQ/Bot/test1.md'
      - Website:
        - 'Test': 'General FAQ/Bot/test1.md'
    - Tutorials:
      - 'Test': Tutorials/test2.md    

