# Project information
site_name: 'LenoxBot Documentation'
site_description: 'LenoxBot offers many cool new features to your Discord Server!'
site_author: 'LenoxBot'
site_url: 'https://lenoxbot.com'

# Repository
repo_name: 'LenoxBot/LenoxBot-Docs'
repo_url: 'https://github.com/LenoxBot/LenoxBot-Docs'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 LenoxBot'

# Configuration
theme:
  favicon: 'lenoxbot.png'
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/lenoxbot'
    - type: 'github'
      link: 'https://github.com/LenoxBot/LenoxBot-Docs/'

#Pages
pages:
    - 'index.md'
    - Getting started: gettingstarted.md
    - General FAQ:
      - Bot:
        - 'My credits are gone. What can I do?': 'General FAQ/Bot/my credits are gone.md'
      - Help:
        - 'Where can I receive support?': 'General FAQ/Help/where can I receive support.md'
      - Website:
        - 'Dashboard': 'General FAQ/Website/dashboard.md'
    - Tutorials:
      - 'Set up application module': Tutorials/set up application module.md    

