# Project information
site_name: 'LenoxBot Documentation'
site_description: 'LenoxBot offers many cool new features to your Discord Server!'
site_author: 'LenoxBot'
site_url: 'https://lenoxbot.com'

# Repository
repo_name: 'LenoxBot/LenoxBot-Docs'
repo_url: 'https://github.com/LenoxBot/LenoxBot-Docs'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 LenoxBot'

# Configuration
theme:
  favicon: 'lenoxbot.png'
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/lenoxbot'
    - type: 'github'
      link: 'https://github.com/LenoxBot/LenoxBot-Docs/'

#Pages
pages:
    - 'index.md'
    - Getting started: gettingstarted.md
    - General FAQ:
      - Bot:
        - 'My credits are gone': 'General FAQ/Bot/my credits are gone.md'
      - Help:
        - 'Support': 'General FAQ/Help/support.md'
      - Website:
        - 'Dashboard': 'General FAQ/Website/dashboard.md'
    - Tutorials:
      - 'Set up application module': Tutorials/application module.md
    - Commands:
      - 'Administration': Commands/administration.md  
      - 'Moderation': Commands/moderation.md
      - 'Help': Commands/help.md
      - 'Music': Commands/music.md
      - 'Fun': Commands/fun.md
      - 'Searches': Commands/searches.md
      - 'NSFW': Commands/nsfw.md
      - 'Utility': Commands/utility.md
      - 'Application': Commands/application.md
      - 'Currency': Commands/currency.md
      - 'Tickets': Commands/tickets.md

